[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
chain_id = 80002
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
[rpc_endpoints]
polygon_amoy = "${RPC_URL}"
